name: Convert Conf Files

on:
  schedule:
    - cron: "0 1 * * *" # every day
  workflow_dispatch:

jobs:
  convert_conf_files:
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v2.2.2
      with:
        python-version: 3.9
    
    - name: Install dependencies
      run: pip3 install glob2

    - name: Convert Conf Files
      env:
        CN_DNS: quic://dns.alidns.com
        THE_DNS: 127.0.0.1:7874
      run: python convert.py

    - name: Check for changes
      run: |
        if ! git diff --quiet; then
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          current_time=$(date +'%Y-%m-%d %H:%M:%S')
          git add .
          git commit -m "Convert conf files to txt - $current_time"
        else
          echo "No changes to commit."
        fi

    - name: Push changes
      uses: ad-m/github-push-action@v0.6.0
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: master
